# Push config for the main "Test phrase" project only.
# Run with: phrase push --config=.phrase.mainapp.push.yml --tag=mainapp
phrase:
  project_id: 676b516aed3001e0832302a9060d154f

  push:
    sources:
      - file: ./Properties/Resources.resx
        file_format: resx
        params:
          locale_id: en
          update_translations: true
          autotranslate: true
